# General

set-window-option -g mode-keys vi

bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

set -g mouse on
set -g base-index 1

set -sg escape-time 0

set -g status-bg default
set-option -g status-style bg=default
set -g status-fg "#C5C9C7"

# Binds

unbind C-b
set -g prefix C-\;
bind -n C-\; send-prefix

bind-key C-d display-popup -B -E "tmuxs"
bind-key C-w display-popup -B -E "tmuxw"
bind-key e run-shell 'tmux new-window -n edit-tmuxs "$EDITOR $HOME/.config/tmuxs"'

bind C-l switch-client -l

# Source

source -q /etc/.env.tmux.conf
