#!/bin/bash

cbox="/home/con/containers"
ctarget=$(find $cbox/ -mindepth 1 -maxdepth 1 -type d | tr ' ' '\n' | fzf)

if [ -z $ctarget ]; then
    exit 1
fi

SHARE_DIR="/tmp/con-share"
if [ ! -d "$SHARE_DIR" ]; then
    mkdir -p "$SHARE_DIR"
    chmod 777 "$SHARE_DIR"
fi

systemd-nspawn -D $ctarget --background=
