#!/usr/bin/env bash

# I'M ROOT

if [[ $EUID -ne 0 ]]; then
    echo "Run this script as root"
    exit 1
fi

# DEF

CON_SETUP_SCRIPT_URL="https://raw.githubusercontent.com/wtrce-remastered/dots/master/arch-container-setup.sh"

CON_BOX_PATH="/var/rsd/containers"
CON_BOX_PBITS="700"

CON_CONFIGS_PATH="/etc/systemd/nspawn"

# CON BOX SETUP IF NOT EXIST

if ! [ -d "$CON_BOX_PATH" ]; then
    mkdir -p "$CON_BOX_PATH"
    chmod "$CON_BOX_PBITS" "$CON_BOX_PATH"
fi

# ARGUMENTS

con_name="$1"
if [ -z "$con_name" ]; then
    echo "Usage: $0 <container_name>"
    exit 1
fi

con_path="$CON_BOX_PATH/$con_name"
if [ -d "$con_path" ]; then
    echo "$con_path already exists"
    exit 1
fi

# CREATING

mkdir -p "$con_path" \
    && pacstrap -K -c "$con_path" base \
    && systemd-nspawn -D "$con_path" --background= /bin/bash -c "echo 'Pass for root' && passwd && curl -sL $CON_SETUP_SCRIPT_URL | /bin/bash" \
    && mkdir -p "$CON_CONFIGS_PATH" && ln -sf "$CON_BOX_PATH/default.nspawn" "$CON_CONFIGS_PATH/$con_name.nspawn"
